server:
  port: 8082 # 端口

spring:
  application:
    name: ms-oauth2-server # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 420130zxc
    url: jdbc:mysql://127.0.0.1:3306/db_volunteer?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    database: 1
    password: 420130zxc
  # swagger
  swagger:
    base-package: cn.sicnu.oauth
    title: swagger-title

# Oauth2
client:
  oauth2:
    client-id: appId # 客户端标识 ID
    secret: 123456 # 客户端安全码
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 2592000
    refresh-token-validity-time: 2592000
    # 客户端访问范围
    scopes:
      - api
      - all

mail:
  server:
    host: smtp.qq.com
    port: 587
    username: 974212451@qq.com
    password:

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
  type-aliases-package: cn.sicnu.common.model.entity
  mapper-locations: classpath:mapper/**Mapper.xml


# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点

logging:
  level:
    org.springframework: debug
    cn.sicnu: debug
  pattern:
    console: '%d{yyyy-MM-dd:hh.mm.ss} [%thread] %-5level %logger{50} - %msg%n'