server:
  port: 8084

spring:
  application:
    name: ms-activity

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 420130zxc
    url: jdbc:mysql://127.0.0.1/db_volunteer?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false

  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    password: 420130zxc
    database: 0

  swagger:
    base-package: cn.sicnu.school
    title: swagger-title

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

oauth2:
  client:
    client-id: appId
    secret: 123456
    grant_type: password
    scope: api


# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.sicnu.common.model.entity
  mapper-locations: classpath:mapper/**Mapper.xml


logging:
  level:
    org.springframework: debug
    cn.sicnu: debug
  pattern:
    console: '%d{yyyy-MM-dd:hh.mm.ss} [%thread] %-5level %logger{50} - %msg%n'

basic:
  auth:
    client-id: appId # 客户端标识 ID
    secret: 123456 # 客户端安全码